services:
  - type: web
    name: clubcardmonitoring
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: clubcarddb
          property: connectionString
    preDeployCommand: |
      python manage.py collectstatic --noinput
      python manage.py migrate
