# Generated by Django 5.2.3 on 2025-06-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardstats',
            name='impact',
            field=models.FloatField(default=0.0),
        ),
    ]
