# Generated by Django 5.2.3 on 2025-06-29 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardStatsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('raw_payload', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='cardstats',
            name='played_games',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardstats',
            name='played_wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardstats',
            name='seen_games',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardstats',
            name='seen_wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
