# Generated by Django 5.2.3 on 2025-06-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_cardstats_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardstats',
            name='card_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
