# Generated by Django 5.2.3 on 2025-06-30 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_cardstatslog_cardstats_played_games_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('last_processed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='cardstatslog',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardstatslog',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
