# Generated by Django 5.2.3 on 2025-07-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_processingstate_cardstatslog_is_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardstatslog',
            name='member_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
