# Generated by Django 5.2.3 on 2025-07-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_cardstatslog_member_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardstatslog',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cardstatslog',
            name='nickname',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
