# Generated by Django 5.2.3 on 2025-07-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_cardstatslog_game_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardstatslog',
            name='game_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cardstatslog',
            name='goes_first',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
