# Generated by Django 5.2.3 on 2026-08-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_cardstatslog_game_token_cardstatslog_goes_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardstatslog',
            name='ip_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
